apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-virtualservice
  namespace: frontend
spec:
  hosts:
  - "user.k8s.dearsoft.tech" # Your actual domain
  gateways:
  - istio-ingressgateway  # Reference to the default Istio ingress gateway
  http:
  - route:
    - destination:
        host: frontend-service
        subset: stable
      weight: 01
    - destination:
        host: frontend-service
        subset: canary
      weight: 99
